development:
  adapter: mysql
  encoding: utf8
  database: researchnation_development
  username: root
  password: rootD3velopers

test:
  adapter: mysql
  encoding: utf8
  database: researchnation_test
  username: root
  password:

production:
  adapter: mysql
  encoding: utf8
  database: researchnation_production
  username: root
  password: rootD3velopers
