defaults:
    install_options: --include-dependencies --no-ri --no-rdoc
gems:
  - name: facebooker
    version: 1.0.75
  - name: koala
    version: 0.9.1
  - name: aws-s3
    version: 0.6.2
  - name: i18n
    version: 0.4.2
  - name: monkeywrench
    version: 0.1.7
  - name: rscribd
    version: 1.2.0
  - name: prawn
    version: 0.11.1
- name: time_diff
    version: 0.2.1
