development:
  access_key: AKIAII5FB3QB3457XHKQ
  secret_key: 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
  bucket: 'Researchnation'
  images_bucket: 'Researchnation_images'

test:
  access_key: AKIAII5FB3QB3457XHKQ
  secret_key: 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
  bucket: 'Researchnation'

production:
  access_key: AKIAII5FB3QB3457XHKQ
  secret_key: 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
  bucket: 'Researchnation'
  images_bucket: 'Researchnation_images'

